#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
umask 077

script_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
certificate_cli="$script_directory/lan-certificates.py"
state="$HOME/.local/share/voidstation-lan-ca"
ENV_FILE="$state/wizard.env"

if (($# > 1)) || [[ ${1:-} == --help ]]; then
  printf 'Usage: %s [SERVER_LAN_IP]\nRun on your Arch laptop as your normal user, not on the Server or with sudo.\n' "$0"
  if (($# > 1)); then exit 64; fi
  exit 0
fi
[[ $(id -u) != 0 ]] || { printf 'Run this wizard as your normal Arch user, not root.\n' >&2; exit 1; }
for executable in python3 openssl ssh scp; do
  command -v "$executable" >/dev/null || { printf 'Missing required command: %s\n' "$executable" >&2; exit 1; }
done
[[ ! -L "$ENV_FILE" ]] || { printf 'Refusing a symlinked wizard configuration.\n' >&2; exit 1; }

banner "Voidstation LAN certificates"
stage "Issue or renew on this Arch laptop"
say "The encrypted signing key stays in $state/ca on this laptop."
say "No private CA key will be transferred to the Server or another device."
if [[ -n ${1:-} ]]; then LAN_IP=$1; else ask LAN_IP 'Server reserved LAN IPv4 address:'; fi
python3 -c 'import ipaddress,sys; a=ipaddress.IPv4Address(sys.argv[1]); assert any(a in ipaddress.ip_network(n) for n in ["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16"]), "Use an RFC1918 LAN IPv4 address"' "$LAN_IP"
confirm "Create or renew a certificate for https://$LAN_IP:3000?" || exit 0
result="$(python3 "$certificate_cli" issue --ip "$LAN_IP" --state-dir "$state")"
bundle="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["bundle"])' <<<"$result")"
ca_certificate="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["ca_certificate"])' <<<"$result")"
android_certificate="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["android_certificate"])' <<<"$result")"
fingerprint="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["fingerprint"])' <<<"$result")"
write_env LAN_IP "$LAN_IP"
[[ ! -L "$state/public/fingerprint.txt" ]] || { printf 'Refusing a symlinked fingerprint file.\n' >&2; exit 1; }
printf '%s\n' "$fingerprint" > "$state/public/fingerprint.txt"
say "Public CA SHA-256 fingerprint: $fingerprint"
say "Server bundle: $bundle"

stage "Trust the CA on this Arch laptop"
say "This adds your dedicated CA to this computer's trust store. It may ask for sudo."
say "CA fingerprint: $fingerprint"
if confirm 'Install CA trust on this computer now?'; then
  python3 "$certificate_cli" trust-arch --ca "$ca_certificate" --fingerprint "$fingerprint" --yes
else
  SKIPPED+=("Arch laptop trust installation")
fi

stage "Transfer only the server bundle over SSH"
remote_directory=""
if confirm 'Transfer the server certificate and installer now?'; then
  ask SSH_DEST 'Server SSH login, for example owner@server:'
  [[ $SSH_DEST =~ ^[a-zA-Z_][a-zA-Z0-9_-]*@[a-zA-Z0-9][a-zA-Z0-9.-]*$ ]] || {
    printf 'Use user@hostname or user@IPv4, without spaces or SSH options.\n' >&2; exit 1;
  }
  say "Verify the Server's SSH host key if SSH asks. Never bypass that check."
  remote_directory="$(ssh -o StrictHostKeyChecking=ask -- "$SSH_DEST" "python3 -c 'import os,tempfile; p=tempfile.mkdtemp(prefix=\"voidstation-lan-import-\",dir=os.path.expanduser(\"~\")); os.mkdir(p+\"/bundle\",0o700); print(p)'")"
  [[ $remote_directory =~ ^/[a-zA-Z0-9_./-]+$ ]] || { printf 'Unexpected remote staging path; transfer stopped.\n' >&2; exit 1; }
  scp -o StrictHostKeyChecking=ask -- "$bundle/cert.pem" "$bundle/key.pem" "$bundle/ca.pem" "$SSH_DEST:$remote_directory/bundle/"
  scp -o StrictHostKeyChecking=ask -- "$certificate_cli" "$SSH_DEST:$remote_directory/lan-certificates.py"
  write_env SSH_DEST "$SSH_DEST"
  say "The three-file bundle is staged in $remote_directory/bundle on the Server."
else
  SKIPPED+=("SSH transfer and Server certificate installation")
fi

stage "Install on the Ubuntu Server"
if [[ -n $remote_directory ]]; then
  say "This replaces only /var/lib/voidstation/lan-tls, keeping a backup when needed."
  say "It does not restart the application or change the firewall."
  say "The installer refuses an unexpected replacement CA."
  printf -v install_command 'sudo python3 %q install --ip %q --bundle %q' "$remote_directory/lan-certificates.py" "$LAN_IP" "$remote_directory/bundle"
  if confirm 'Install these certificates on the Server now through SSH and sudo?'; then
    ssh -t -o StrictHostKeyChecking=ask -- "$SSH_DEST" "$install_command"
    say "Remove the remote staging directory after successful deployment. It holds a server private key."
  else
    SKIPPED+=("Server certificate installation")
    say "Run this later in a terminal on the Server:"
    say "$install_command"
  fi
else
  say "Transfer was skipped; the certificate files remain on this laptop only."
fi

handoff="$state/next-steps.txt"
[[ ! -L "$handoff" ]] || { printf 'Refusing a symlinked handoff file.\n' >&2; exit 1; }
{
  printf 'CA fingerprint: %s\nPublic Arch certificate: %s\nPublic Android certificate: %s\n' "$fingerprint" "$ca_certificate" "$android_certificate"
  if [[ -n $remote_directory ]]; then
    printf '\nUbuntu Server, if installation was skipped:\n%s\n' "$install_command"
    printf 'Remote staging directory, remove only after verification: %s\n' "$remote_directory"
  else
    printf '\nServer transfer was skipped. Re-run the wizard to transfer: %s\n' "$bundle"
  fi
  printf '\nArch desktop, after copying ONLY ca.pem and lan-certificates.py:\npython3 lan-certificates.py trust-arch --ca ca.pem --fingerprint %q\n' "$fingerprint"
  printf '\nAndroid: copy only voidstation-ca.crt; Settings > Install a certificate > CA certificate.\n'
  printf '\nCertificate setup alone does not enable LAN access. The approved firewall/configuration cutover and ./deploy.sh remain separate.\n'
} > "$handoff"

stage "Arch desktop and Android"
say "The Server command and these client instructions are saved in $handoff"
say "Copy ONLY the public files below to your other devices."
say "Arch desktop: $ca_certificate"
say "Android: $android_certificate"
say "Expected CA SHA-256 fingerprint: $fingerprint"
say "On the Arch desktop, copy lan-certificates.py too, then run:"
printf '  python3 lan-certificates.py trust-arch --ca ca.pem --fingerprint %q\n' "$fingerprint"
say "On Android, transfer voidstation-ca.crt by USB or another trusted channel."
say "Search Settings for Install a certificate, choose CA certificate, and select that file."
say "Android requires you to approve this installation. Menu names vary by phone."
say "Restart your browsers. Firefox may need a separate Authorities import."
SKIPPED+=("Arch desktop and Android trust, then approved LAN deployment and physical-client checks")
pause 'Press Enter after reviewing the client instructions.'
finish
say "Exact next commands and public certificate paths: $handoff"
say "No application deployment or firewall change was performed by this wizard."
say "Certificate setup alone does not enable LAN access. Follow docs/deployment.md for the approved cutover."
say "Keep an encrypted offline backup of $state/ca and its passphrase separately."
say "Renew before expiry by re-running this wizard on THIS laptop with the SAME state directory."
